language: python
python:
    - "2.7"

install:
    - pip install -r package/requirements.txt --extra-index-url https://testpypi.python.org/pypi
    - pip install cloudshell-shell-core --extra-index-url https://testpypi.python.org/pypi
    - pip install -r test_requirements.txt
    - pip install coveralls

script:
    - pushd package
    - python setup.py develop
    - popd
    - python runtests.py --with-coverage  --cover-package=package --exclude-dir=integration

after_success:
    coveralls
    
notifications:
    webhools: https://qualisystems.getbadges.io/api/app/webhook/63350e33-4119-49c3-8127-075aaa022926
